name: CI/CD
on:
  push:
    branches-ignore:
      - 'dependabot/**'
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
      - name: Build
        run: |
          composer install --no-dev --optimize-autoloader
          composer box-install
          # Warm the symfony cache so it gets bundled with phar.
          ./bin/acli
          composer box-compile
          echo "$(curl -s --upload-file build/acli.phar https://transfer.sh/acquia-cli.phar)"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/acquia-cli.phar
